### ISSUE TITLE
前来求教

### ISSUE THREAD

**Issue by bsns** [preke/Spiders#1]
雷猴啊，最新我也在学习爬虫，在用大众点评练手，写到一部分时卡住，接下来要进行把评论者的id存储时，遇到了思路上的问题，即创建几张表的问题还没想清楚（我在用mysql），所以试图运行你的代码来提供思路。
  然而在osx上一运行（尝试了命令：scrapy crawl Xiuxian），就提示错误：KeyError: 'Spider not found: Xiuxian'，所以请问楼主的运行环境（比如系统，命令），因为没找到readme之类的文档，另外针对多对多的关系（商家和用户）是创建几张表，大概是如何存储的。多谢指教。

**Comment by preke** [comment]
嗯嗯，是这样的，scrapy crawl 后面的参数是爬虫的具体名字，在每个spider类中用name定义，比如本项目中有url_spider.py，我在里面定义的name属性是“url”，想运行这个爬虫命令则是scrapy crawl url
如果你想要用本项目帮助你理解，建议你先去看看scrapy的教程
大众点评的反爬机制是有些棘手的，我试过自己开虚拟机，买代理等等方法
这里有一些tips. http://blog.csdn.net/u013398398/article/details/53676515
关于这个项目，有兴趣可以继续交流
